#!/usr/bin/env python3
##
## EPITECH PROJECT, 2025
## G-MAT-100-LYN-1-1-101pong
## File description:
## 101pong.py
##

import sys
import math

def print_help():
    print("USAGE")
    print("    ./101pong x0 y0 z0 x1 y1 z1 n")
    print("DESCRIPTION")
    print("    x0 ball abscissa at time t - 1")
    print("    y0 ball ordinate at time t - 1")
    print("    z0 ball altitude at time t - 1")
    print("    x1 ball abscissa at time t")
    print("    y1 ball ordinate at time t")
    print("    z1 ball altitude at time t")
    print("    n time shift (greater than or equal to zero, integer)")
    sys.exit(0)

def calcul(x0, y0, z0, x1, y1, z1, n):
    speed = [0, 0, 0]
    coordinate = [0, 0, 0]

    speed[0] = (float(x1) - float(x0))
    speed[1] = (float(y1) - float(y0))
    speed[2] = (float(z1) - float(z0))
    coordinate[0] = float(x1) + (speed[0] * float(n))
    coordinate[1] = float(y1) + (speed[1] * float(n))
    coordinate[2] = float(z1) + (speed[2] * float(n))

    if speed[0] == 0 and speed[1] == 0 and speed[2] == 0:
        angle = 0.0
    else:
        angle = math.degrees(abs(math.atan2(speed[2], math.sqrt(speed[0]**2 + speed[1]**2))))

    return speed, coordinate, angle

def print_result(x0, y0, z0, x1, y1, z1, n):
    try:
        speed = calcul(x0, y0, z0, x1, y1, z1, n)[0]
        coordinate = calcul(x0, y0, z0, x1, y1, z1, n)[1]
        angle = calcul(x0, y0, z0, x1, y1, z1, n)[2]

        print("The velocity vector of the ball is:")
        print(f"({speed[0]:.2f}, {speed[1]:.2f}, {speed[2]:.2f})")
        print(f"At time t + {n}, ball coordinates will be:")
        print(f"({coordinate[0]:.2f}, {coordinate[1]:.2f}, {coordinate[2]:.2f})")

        if float(z1) * speed[2] > 0:
            print("The ball won't reach the paddle.")
            sys.exit(0)

        print("The incidence angle is:")
        print(f"{angle:.2f} degrees")
        sys.exit(0)
    except Exception:
        sys.exit(84)

def check_type(argv):
    try:
        x0 = float(argv[1])
        y0 = float(argv[2])
        z0 = float(argv[3])
        x1 = float(argv[4])
        y1 = float(argv[5])
        z1 = float(argv[6])
        n = int(argv[7])
        if n < 0:
            sys.exit(84)
        print_result(x0, y0, z0, x1, y1, z1, n)
    except ValueError:
        sys.exit(84)
    except Exception:
        sys.exit(84)

def main():
    try:
        if len(sys.argv) == 2 and sys.argv[1] == "-h":
            print_help()
        elif len(sys.argv) == 8:
            check_type(sys.argv)
        else:
            sys.exit(84)
    except SystemExit:
        raise
    except Exception:
        sys.exit(84)

if __name__ == '__main__':
    main()
