#!/usr/bin/env python3
##
## EPITECH PROJECT, 2025
## Projet [WSL: Ubuntu-24.04]
## File description:
## 102architect.py
##

import sys
import math
from flags import h_flag, t_flag, z_flag, r_flag, s_flag, Architect

def main():
    try:
        parser(sys.argv)
        exit(0)
    except ValueError as e:
        print(e)
        sys.exit(84)
    except Exception as e:
        print(e)
        sys.exit(84)

def parser(argv):
    last_flag = ""
    args = [argv[1], argv[2], 0, 0, 0, 0, 0, 0]
    for i in range(len(argv)):
        if (argv[i][0] == "-"):
            last_flag = argv[i]
        if argv[i] == "-t":
            args[2] = argv[i + 1]
            args[3] = argv[i + 2]
            archi = Architect(*args)
            t_flag(args, archi, last_flag)
        if argv[i] == "-z":
            args[4] = argv[i + 1]
            args[5] = argv[i + 2]
            archi = Architect(*args)
            z_flag(args, archi, last_flag)
        if argv[i] == "-r":
            args[6] = argv[i + 1]
            archi = Architect(*args)
            r_flag(args, archi, last_flag)
        if argv[i] == "-s":
            args[7] = argv[i + 1]
            archi = Architect(*args)
            s_flag(args, archi, last_flag)
        if argv[i] == "-h":
            h_flag()

if __name__ == '__main__':
    main()