#!/usr/bin/env python3
##
## EPITECH PROJECT, 2025
## Projet [WSL: Ubuntu-24.04]
## File description:
## 102architect
##

import sys
import math
from flags import h_flag, Architect

def main():
    try:
        parser(sys.argv)
        exit(0)
    except ValueError as e:
        print(e)
        sys.exit(84)
    except Exception as e:
        print(e)
        sys.exit(84)

def t_flag(archi, last_flag, identity_matrix):
    return_matrix = archi.translation(identity_matrix)
    if last_flag == "-t":
        archi.print_result(identity_matrix)
    return return_matrix

def z_flag(archi, last_flag, identity_matrix):
    return_matrix = archi.scaling(identity_matrix)
    if last_flag == "-z" :
        archi.print_result(identity_matrix)
    return return_matrix

def r_flag(archi, last_flag, identity_matrix):
    return_matrix = archi.rotate(identity_matrix)
    if last_flag == "-r":
        archi.print_result(identity_matrix)
    return return_matrix

def s_flag(archi, last_flag, identity_matrix):
    return_matrix = archi.reflection(identity_matrix)
    if last_flag == "-s":
        archi.print_result(identity_matrix)
    return return_matrix

def parser(argv):
    last_flag = ""
    args = [argv[1], argv[2], 0, 0, 0, 0, 0, 0]
    archi = Architect(*args)
    identity_matrix = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    for i in range(len(argv)):
        if (argv[i][0] == "-"):
            last_flag = argv[i]
        if argv[i] == "-t":
            args[2] = argv[i + 1]
            args[3] = argv[i + 2]
            identity_matrix = t_flag(archi, last_flag, identity_matrix)
        if argv[i] == "-z":
            args[4] = argv[i + 1]
            args[5] = argv[i + 2]
            identity_matrix = z_flag(archi, last_flag, identity_matrix)
        if argv[i] == "-r":
            args[6] = argv[i + 1]
            identity_matrix = r_flag(archi, last_flag, identity_matrix)
        if argv[i] == "-s":
            args[7] = argv[i + 1]
            identity_matrix = s_flag(archi, last_flag, identity_matrix)
        if argv[i] == "-h":
            h_flag()

if __name__ == '__main__':
    main()